### ISSUE TITLE
Incompatible acceptances: FALSE vs TRUE

### ISSUE THREAD

**Issue by z11panyan** [LearnLib/learnlib#76] opened 2021-05-20 09:30 UTC
When I took the random DFA as the experimental object, the error "Incompatible acceptances: FALSE vs TRUE"  occurred in IncrementalDFADAGBuilder.java. By debugging the class IncrementalDFADAGBuilder, the execution result of the statement , "sig.successors.array[idx] = succ" (in the function updateSignature ), puzzles me. The type of the parameter "succ"  is State, and it changed after the executing of the above statement. As shown in the following figure：
<img width="618" alt="捕获" src="https://user-images.githubusercontent.com/16456661/118955224-147c0280-b991-11eb-82d9-c6eecf8f1b10.PNG">
<img width="637" alt="捕获1" src="https://user-images.githubusercontent.com/16456661/118955232-1645c600-b991-11eb-99e4-06e9c39f139d.PNG">
Thus, the longer word will lead to the error   "Incompatible acceptances: FALSE vs TRUE".

**Comment by mtf90** [comment] 2021-05-20 11:04
Is there a way for you to provide a minimal working example so that we can reproduce the error?


Otherwise, there was a [bug](https://github.com/LearnLib/automatalib/commit/b07fb64331d510839693f5eb7e8c5aee35b3227f) in the DAG-based caches that has been fixed in the current development version of AutomataLib. You could also try to use the [current development version](https://github.com/LearnLib/learnlib/wiki/Using-Development-Versions) of LearnLib and see, if the error still exists. (You might want to check the [AutomataLib](https://github.com/LearnLib/automatalib/blob/develop/CHANGELOG.md) and [LearnLib changelogs](https://github.com/LearnLib/learnlib/blob/develop/CHANGELOG.md) before, to see if you are affected by other changes as well).

**Comment by z11panyan** [comment] 2021-05-20 12:47
[error3.dfa.gz](https://github.com/LearnLib/learnlib/files/6515869/error3.dfa.gz)
This is the error dfa. The format is consistent with the example of the Paper "The TTT Algorithm: A Redundancy-Free
Approach to Active Automata Learning".

**Comment by mtf90** [comment] 2021-05-20 19:32
Which equivalence and learning algorithm did you use? Alternatively, you can also post the complete `.java` file of your learning setup (which preferably provokes the above error when executing its `main` method).

**Comment by z11panyan** [comment] 2021-05-21 02:29
[dfa.tar.gz](https://github.com/LearnLib/learnlib/files/6519644/dfa.tar.gz)

This is the added files and the path is "learnlib/algorithms/active/ttt/src/test/java/de/learnlib/algorithms/ttt/dfa". 
<img width="398" alt="捕获2" src="https://user-images.githubusercontent.com/16456661/119072961-02e13c00-ba1f-11eb-9292-9fbb72998b63.PNG">
This is the catalog of the added files. In addition, the equivalence algorithm is wp-method, and the learning algorithm is LStar. What else can I offer?

**Comment by mtf90** [comment] 2021-05-22 23:11
An intermediate update: I was able to reproduce the issue and it actually looks like a bug in the DFADAGBuilder. But I need some more time to actually piece together what goes wrong here. Do you mind if I use (some of) your code to create a testcase?

For now, you can use `DFACaches.createTreeCache` as an alternative. This type of cache will require a little bit more system memory, but it will give you the same query performance and you should be able to successfull execute your experiments.

**Comment by z11panyan** [comment] 2021-05-23 02:16
Of course not,  as long as it is helpful for you. And I will try to use DFACaches.createTreeCache as an alternative. 

Another issue is the queryCache. The core code of the function processQueries is as follows.
`
 final Collection<ProxyQuery<I>> unanswered = queryCache(queries); 

 delegate.processQueries(unanswered);

 updateCache(unanswered);
`
I think there is an issue. If there are two identical unanswered queries in the Collection "queries", the number of unique query will be increased by 2. Could you analyse this issue?

**Comment by mtf90** [comment] 2021-05-23 22:56
> Another issue is the queryCache. The core code of the function processQueries is as follows.
> `
> ...
> `
> I think there is an issue. If there are two identical unanswered queries in the Collection "queries", the number of unique query will be increased by 2. Could you analyse this issue?

You are correct. However, this is currently by design because in order to answer queries we need to call the `answer` method on every query object. Thus, we cannot "merge" duplicate queries within a single batch without copying (and aggregating) every query. But to be fair, we do exactly that (copying) in the Mealy case, because of the even greater optimization potential of prefix-closedness. It's a valid point to think about for the DFA case as well.

Do you have encountered any specific situation where this is a problem? I think mostly table-based algorithms (L* variants) may be affected by this when using prefix-closed row labels and suffix-closed discriminators (columns). Most tree-based learners use much smaller batches when classifying states and the queries withing each batch should be distinct.

**Comment by z11panyan** [comment] 2021-05-24 01:21
Through experiments, table-based algorithms are affected by this issue, but it has little effect.

**Closed** 2021-06-14 22:36 UTC

**Comment by mtf90** [comment] 2021-06-14 22:52
I finally managed to find the culprit and provide a fix for the issue. Looking at the diff, the devil is always in the details :D.

Are you fine with using a [development version](https://github.com/LearnLib/learnlib/wiki/Using-Development-Versions) of LearnLib (respectively AutomataLib) or would you prefer a separate bugfix release?


Also, regarding you remark on handling in-batch duplicates, I created a separate issue #78.

**Comment by z11panyan** [comment] 2021-06-15 01:24
Thanks for maintaining this great library! For me,  a development version is fine.
