### ISSUE TITLE
running example

### ISSUE THREAD

**Issue by soojinm** [LearnLib/learnlib#38] opened 2016-08-18 06:18 UTC
Hi, I am a bit confused to "how do I run example code in the github?" 
I am using command line. What I have done is:
in learlib/examples, I ran "mvn install" which produced jar file. 
I ran " java -jar ./target/learnlib-examples-0.12.1-SNAPSHOT.jar" which throws "no manifest main error" 

Seems like I am not understanding something - so how do I exactly run 3 example codes using command line? Thankss

**Comment by Jaxan** [comment] 2016-08-29 12:09
There are three examples to run, and you have to specify which one you want to run:
```
java -cp ./learnlib.jar de.learnlib.examples.example1.Example
```

**Comment by aschieweck** [comment] 2016-10-16 10:32
The issue is now nearly 2 month old and no follow up questions to the proposed fix were asked. So I will close this issue, but please feel free to ask more questions regarding this problem in this thread.

**Closed by aschieweck** 2016-10-16 10:32 UTC
Labels: support
