### ISSUE TITLE
Observation Table is not being opened in Browser

### ISSUE THREAD

**Issue by bazali786** [LearnLib/learnlib#45] opened 2017-08-24 09:51 UTC
Hello!
Please help me.
When i try to run the code examples of LearnLib e.g, of CoffeeMachine it prodcuced output (i.e., Learn Machine model by GraphViz) but the final Observation Table is not being Opened in Browser.

Error:

![error2](https://user-images.githubusercontent.com/30205819/29660768-aed8df64-88f4-11e7-878c-2fc69395fb4a.jpg)

**Comment by mtf90** [comment] 2017-08-28 15:01
Could you please post the complete stacktrace as text? The interesting part is unfortunately cut off in your screenshot :(. One [result](https://stackoverflow.com/questions/31367967/open-in-default-browser-exception) of a quick google search shows, that you are not the only one with an error like this.

As a temporary workaround: Could you check if the file listed in the exception exists and open it manually? (You might have to take care and not exit the Java process, as temporary files may be deleted once the JVM terminates

**Comment by mtf90** [comment] 2017-10-16 08:30
Any chance to provide additional information? Since we cannot reproduce this error, I will otherwise close this issue as not reprodrucible.

**Comment by mtf90** [comment] 2017-11-28 15:01
I'm closing this issue due to the missing feedback and us not being able to reproduce the problem. If this is actually a problem in LearnLib, feel free to re-open the ticket.

If you have general questions on using LearnLib, make sure to check out our [Q&A list](https://groups.google.com/d/forum/learnlib-qa), so that we can use the issue tracker for actual issues.

**Closed by mtf90** 2017-11-28 15:01 UTC
