### ISSUE TITLE
NLStarLearner does not learn 

### ISSUE THREAD

**Issue by garganti** [LearnLib/learnlib#60] opened 2018-09-26 16:58 UTC
Hello. 
I'm trying to use learnlib for learn automata by the L* Angluin algorthm. For that I use leranlinb:
- BricsDFA to model the automata I have to learn (I use e regexp to specify the oracle the learner has to learn)
- MembershipOracle as oracle to see if a word is accepted or not by the oracle
- SimulatorEQOracle.DFASimulatorEQOracle to check equivalence (the teacher)
- NLStarLearner the real learner.
I have written the following code:
~~~~
public static void main(String[] args) {
	// build the alphabet: from a to z
	List<Character> readableAscii = new ArrayList<>();
	for(char c = 'a'; c<= 'z';c++) readableAscii.add(c);	
	Alphabet<Character> alphabet = new ArrayAlphabet<>(readableAscii.toArray(new Character[readableAscii.size()]));
	// 1. build the learner - the oracle now it is a given automaton 
	RegExp r = new RegExp("[a-b]{2}");
	Automaton automaton = r.toAutomaton();
	BricsDFA dfa = new BricsDFA(automaton,true);
	// oracale
	MembershipOracle<Character, Boolean> oracle = new SimulatorOracle.DFASimulatorOracle<>(dfa);				
	// equivalent checker
	SimulatorEQOracle.DFASimulatorEQOracle<Character> eqautomata = new SimulatorEQOracle.DFASimulatorEQOracle<Character>(dfa);
        // the learner
        NLStarLearner<Character> learner = new NLStarLearner<>(alphabet, oracle);
	// learn the automaton
	DefaultQuery<Character, Boolean> counterexample = null;
	do {
		if (counterexample == null) {
			learner.startLearning();
		} else {
			boolean refined = learner.refineHypothesis(counterexample);
			if (!refined) {
				System.err.println("No refinement effected by counterexample!");
			}
		}
		counterexample = eqautomata.findCounterExample(learner.getDeterminizedHypothesis(), alphabet);
		System.out.println("cex: " + counterexample);
	} while (counterexample != null);
	// from here on learner.getHypothesisModel() will provide an accurate model
	System.out.println(learner.getDeterminizedHypothesis());
}
~~~~
The problem is that the learner does not learn fro the counter example. I always get the counter example:
cex: Query[?|c / false]
but the learner is not modified.
Could someone help me?

**Comment by mtf90** [comment] 2018-09-27 07:37
Can confirm, this looks like a bug. I'll try to look into it the next days. There are several components where things can go wrong (the Brics determinization process, our Brics wrapper, our NL* implementation or our determinization process)

**Comment by mtf90** [comment] 2018-09-29 20:51
So the problem is, that the regexp transformation + our Brics wrapper yields an automaton whose transition function is only defined for the two symbols `a` and `b`. By defining the learning alphabet as `a-z`, this results in the transformed automaton being only partially defined. As a result, the equivalence tests always yield the word `c` (because there exists a `c` transition for the (total) hypothesis but not for the target automaton). However, `c` is not a valid counterexample, because both are rejected due to the DFA/NFA semantics.


As an immediate workaround you could:

* restrict the learning alphabet to `{a,b}` as well, or
* use a different equivalence algorithm (e.g. WMethod or random words) that does not depend on the internal structure of the target system


We'll have to think about how to properly address this. We could require an input alphabet for our Brics wrapper as well (the Brics automaton class also has a `totalize` function, but it's unfortunately not public) but this problem arises for any automaton that has undefined transitions. While the internal equivalence checker has an optional parameter for ignoring undefined transitions, I don't think this is the right approach here, because we would miss evident counterexamples. Maybe we should just throw an exception/log a warning, if we detect a partial automaton for the given input alphabet. If you like, you can also comment on what your preferred feedback would be from a user-perspective.

**Comment by mtf90** [comment] 2018-10-09 10:17
For now, I updated the `BricsDFA` to allow a flag for totalizing the automaton (as BRICS automata do not allow to limit their input alphabet to certain characters). With this change, you should be able to configure your learning setup as expected.

But I'm tending towards closing this issue as an error on the user-side. You use a structural equivalence check (the `SimulatorEQOracle`) and compare a total automaton (your hypothesis, defined on `a-z`) to a partial one (the BRICS target, defined on `a, b`). From a generic automaton point of view, the separating word is correct. It is only the N/DFA semantics that give you trouble here, which can be easily addressed since partial N/DFAs are just shorthand notations for omitting a sink. (In the `BricsDFA` case it was not possible, which is why I introduced the above changes).

What's your point of view on this issue?

**Comment by mtf90** [comment] 2018-11-25 01:14
@garganti Any updates on this issue?

**Comment by mtf90** [comment] 2019-02-18 14:24
I'm closing this issue due to lack of activity and because from my point of view, the issue is fixed with the changes in the `Brics{NFA,DFA}` class of our just-released version.

If you think, your original issue is not properly addressed by this, feel free to re-open (or comment on) this issue.

**Closed by mtf90** 2019-02-18 14:24 UTC

**Comment by garganti** [comment] 2019-02-18 14:26
I'll try the new solution. For now I'm satisfied with the procedure we set up. If it can be useful, we have also a method for the reverse, from DFA to Brics automaton.
