### ISSUE TITLE
DAG cache is broken

### ISSUE THREAD

**Issue by Jaxan** [LearnLib/learnlib#31] opened 2015-06-04 14:15 UTC
I have a specific mealy machine, with a custom equivalence oracle. For some reason the DHC algorithm induces some loop, where my oracle finds the same counter example over and over again, and the hypothesis still fails that counter example. Here is the explicit case: [dhc is broken?](https://gist.github.com/Jaxan/6fe8454ecc6e0e332704)

**Comment by maikmerten** [comment] 2015-06-06 13:08
After having a quick look over your code, I'm not sure the Machine-instance you're doing your equivalence tests on actually is behaviorally equivalent to the Machine-instance you are doing membership queries on.

During EQs, you are advancing to a specific state using setN(). The provided value then will be wrapped around using different (but hopefully equivalent) logic than what happens in apply(). Of course, if the wrap-around logic happens *not* to be exactly equivalent your Machine for EQs will exhibit diverging behavior that cannot be resolved, leading to an infinite loop.

Can you test what happens when your equivalence oracle only uses Machine#apply just like the membership oracle does? It is usually safest if the system under learning is operated in exactly the same fashion by both types of oracles.

Also it would be nice if someone of the current LearnLib team with a firm understanding of the current state of the involved data structures can have a look on the provided code example - I'm a bit rusty in this regard.

**Comment by misberner** [comment] 2015-06-08 09:44
Having investigated this, the cause seems to be not the DHC algorithm itself, nor the Rivest/Schapire counterexample analysis, but the cache. Constructing the cache using `MealyCaches.createTreeCache(alphabet, oracle)` should fix this.

We have observed an error in the DAG cache earlier, but only on much larger systems, making it near impossible to debug. I hope that this test case will make this somewhat easier... in the meantime, please use the above fix.

(On a side note, your membership oracle is incorrectly implemented: the two parameters in the `answerQuery` method are to be understood as `prefix` and `suffix`, where `prefix` takes the SUL to a certain state, while `suffix` is the test to be executed from that state whose output is examined. Thus, the return value of `answerQuery` should consist of only the output symbols produced in reaction to symbols from the suffix part, not the prefix part. Likewise, line 105 of your example -- `Word<Output> o = m2.answerQuery(word2, Word.fromSymbols());` -- does not make sense with a correctly implemented oracle, since it will only ever return the empty word (as the suffix part is empty).

The reason why this does not cause any problems with learning is, by the way, the fact that you use a cache: a cache "normalizes" each query, i.e., transforming a query (u, v) into (epsilon, uv), in order to avoid having to query true prefixes of another query, and then transforms the answer back to match the query (u, v) by only considering the last |v| output symbols.)

**Comment by mgeske** [comment] 2015-06-09 13:17
Issue is resolved with the fix for https://github.com/misberner/automatalib/issues/12

**Closed by mgeske** 2015-06-09 13:17 UTC
Labels: bug

**Comment by misberner** [comment] 2015-06-10 11:07
@Jaxan: was this the only case where you observed such behavior, or was this a stripped-down version of a more complex setup? Can you confirm that the bug is fixed in the latest 0.12.1-SNAPSHOT ?

**Comment by Jaxan** [comment] 2015-06-22 06:42
@misberner This was the test case, I made this while familiarising myself with LearnLib. I will check the new version soon (I was on holiday for two weeks, hence my late reply).

This prefix/suffix part was only clear to me much later. But I think I did not make a mistake there, since I use this constructor [using only a suffix (I believe)](https://github.com/LearnLib/learnlib/blob/master/core/src/main/java/de/learnlib/oracles/DefaultQuery.java#L52). So the prefix is empty and there is a (non-empty) suffix and answer. But I admit that this is not clear from the code and the distinction prefix/suffix sometimes still puzzles me.

Thanks for (probably) having solved the issue!
