### ISSUE TITLE
maven build failure due to dependencies

### ISSUE THREAD

**Issue by soojinm** [LearnLib/learnlib#37] opened 2016-08-18 01:51 UTC
When running "mvn build," I get a build error saying dependencies.dependency.version is missing for some submodules. 
---------------------------------------------------------------------------------------------------------------------------
[ERROR] The build could not read 1 project -> [Help 1]
org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[ERROR] 'dependencies.dependency.version' for de.learnlib:learnlib-core:jar is missing. @ line 16, column 15

	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:363)
	at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:636)
	at org.apache.maven.DefaultMaven.getProjectsForMavenReactor(DefaultMaven.java:585)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:234)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
[ERROR]   
[ERROR]   The project de.learnlib:learnlib-reuse:0.12.1-SNAPSHOT (/users/soojinm/learnlib/filters/reuse/pom.xml) has 1 error
[ERROR]     'dependencies.dependency.version' for de.learnlib:learnlib-core:jar is missing. @ line 16, column 15
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
---------------------------------------------------------------------------------------------------------------------------

I have followed the documentation on Wiki and added the dependencyManagement to specify the version. Any help on why the build is failing would be appreciated. pom.xml is also attached

[pom.xml.txt](https://github.com/LearnLib/learnlib/files/423988/pom.xml.txt)

**Comment by aschieweck** [comment] 2016-10-16 10:50
I just cloned the develop _branch_ and run `mvn install` without any error. So I am not sure what went wrong in your set up. My only idea is, that you need to run the Maven command on the root of the repository. It seems to me, that you've tried to build the _learnlib-resue_ artifact which depends on _learnib-core_, but you've never build the core artifact before.

I am going to close this issue because I can not reproduce it and its nearly 2 month old. But I will reopen it if more information is provided and/or more questions are asked.

**Closed by aschieweck** 2016-10-16 10:50 UTC
Labels: invalid, support
