### ISSUE TITLE
problems in using APIrefineHypothesis()

### ISSUE THREAD

**Issue by IMhappyZzz** [LearnLib/learnlib#49] opened 2017-10-19 07:29 UTC
I want to use the APIs to learn Hypothesis like this:

```java
learn() {
   boolean flag = true;
   learningAlgorithm.startLearning();
   hypothesis = learningAlgorithm.getHypothesisModel();
   while(flag) {
           counterExample = equivalenceAlgorithm.findCounterExample();
           if(counterExample == null) {
                flag = false;
           } else {
                result= learningAlgorithm.refineHypothesis(counterExample);
                hypothesis = learningAlgorithm.getHypothesisModel();
           }      
           //......get the final HypothesisModel.............          
}
```

but  when i test the program, it  always hung up in refineHypothesis(); will get someHypothesis but no final result. I can't find out what's wrong with it.

**Comment by mtf90** [comment] 2017-10-21 17:16
Dear @IMHappyZzz,

I can see one potential problem with your code: You store the result of `learningAlgorithm.refineHypothesis(counterExample)` in the variable `result`. If you pass a false counterexample to the learning algorithm, which does not trigger an actual hypothesis refinement, the `refineHypothesis` method will return `false`. This information is not propagated to your `flag` variable, so you can potentially run into an infinite loop. 

However, without further information, it is hard to tell what is going wrong. A minimal working example (MWE) which would allow us to reprodruce the error would be the best.

It could also be a problem with your system under learning. If it does not exhibit regular behavior, a regular learning algorithm usually runs into infinite loops. Especially systems, which involve some kind of counting (e.g. a stack datastructure) have these kind of problems. You could check, if the size of the hypothesis increases throught the loop iterations to further pinpoint the issue.

**Comment by mtf90** [comment] 2017-11-28 15:04
I'm closing this issue due to the missing feedback and us not being able to reproduce the problem. If this is actually a problem in LearnLib, feel free to re-open the ticket.

If you have general questions on using LearnLib, make sure to check out our [Q&A list](https://groups.google.com/d/forum/learnlib-qa), so that we can use the issue tracker for actual issues.

**Closed by mtf90** 2017-11-28 15:04 UTC
